package calc

import (
	"github.com/marcetin/wingcal/model"
)

func (w *WingCal) NewMaterijal() {
	w.Materijal = map[int]*model.WingMaterijal{
		0: &model.WingMaterijal{
			Id:        1,
			Naziv:     "Glet masa-gletokol",
			Opis:      "Glet masa-gletokol",
			Obracun:   "Obracun po kilogrammu",
			Jedinica:  "kg",
			Pakovanje: 25,
			Cena:      13.00,
			Slug:      "glet_masa_gletokol",
		},
		1: &model.WingMaterijal{
			Id:        2,
			Naziv:     "Masa za španski zid",
			Opis:      "Masa za španski zid",
			Obracun:   "Obracun po kilogrammu",
			Jedinica:  "kg",
			Pakovanje: 25,
			Cena:      19.00,
			Slug:      "masa_za_spanski_zid",
		},
		2: &model.WingMaterijal{
			Id:        3,
			Naziv:     "Bavalit fasada",
			Opis:      "Bavalit fasada",
			Obracun:   "Obracun po kilogrammu",
			Jedinica:  "kg",
			Pakovanje: 25,
			Cena:      16.00,
			Slug:      "bavalit_fasada",
		},
		3: &model.WingMaterijal{
			Id:        4,
			Naziv:     "Fasada hirofa",
			Opis:      "Fasada hirofa",
			Obracun:   "Obracun po kilogrammu",
			Jedinica:  "kg",
			Pakovanje: 25,
			Cena:      15.00,
			Slug:      "fasada_hirofa",
		},
		4: &model.WingMaterijal{
			Id:        5,
			Naziv:     "Lepak za siporeks blokove",
			Opis:      "Lepak za siporeks blokove",
			Obracun:   "Obracun po kilogrammu",
			Jedinica:  "kg",
			Pakovanje: 25,
			Cena:      9.50,
			Slug:      "lepak_za_siporeks blokove",
		},
		5: &model.WingMaterijal{
			Id:        6,
			Naziv:     "Lepak za keramičke pločice Pk-111",
			Opis:      "Lepak za keramičke pločice Pk-111",
			Obracun:   "Obracun po kilogrammu",
			Jedinica:  "kg",
			Pakovanje: 25,
			Cena:      10.00,
			Slug:      "lepak_za_keramicke_plocice_pk_111",
		},
		6: &model.WingMaterijal{
			Id:        7,
			Naziv:     "Lepak za stiropor",
			Opis:      "Lepak za stiropor",
			Obracun:   "Obracun po kilogrammu",
			Jedinica:  "kg",
			Pakovanje: 25,
			Cena:      10.50,
			Slug:      "lepak_za_stiropor",
		},
		7: &model.WingMaterijal{
			Id:        8,
			Naziv:     "Lepak za kamenu vunu",
			Opis:      "Lepak za kamenu vunu",
			Obracun:   "Obracun po kilogrammu",
			Jedinica:  "kg",
			Pakovanje: 25,
			Cena:      14.00,
			Slug:      "lepak_za_kamenu_vunu",
		},
		8: &model.WingMaterijal{
			Id:        9,
			Naziv:     "Lepak za kamen vajt (beli)",
			Opis:      "Lepak za kamen vajt (beli)",
			Obracun:   "Obracun po kilogrammu",
			Jedinica:  "kg",
			Pakovanje: 25,
			Cena:      44.00,
			Slug:      "lepak_za_kamen_vajt_beli",
		},
		9: &model.WingMaterijal{
			Id:        10,
			Naziv:     "Lepak za keramiku Pk-116",
			Opis:      "Lepak za keramiku Pk-116",
			Obracun:   "Obracun po kilogrammu",
			Jedinica:  "kg",
			Pakovanje: 25,
			Cena:      24.00,
			Slug:      "lepak_za_keramiku_pk_116",
		},
		10: &model.WingMaterijal{
			Id:        11,
			Naziv:     "Glet masa spoljna",
			Opis:      "Glet masa spoljna",
			Obracun:   "Obracun po kilogrammu",
			Jedinica:  "kg",
			Pakovanje: 25,
			Cena:      24.00,
			Slug:      "glet_masa_spoljna",
		},
		11: &model.WingMaterijal{
			Id:        12,
			Naziv:     "Mašinski malter krečno-cementni",
			Opis:      "Mašinski malter krečno-cementni",
			Obracun:   "Obracun po kilogrammu",
			Jedinica:  "kg",
			Pakovanje: 30,
			Cena:      7.10,
			Slug:      "masinski_malter_krecno_cementni",
		},
		12: &model.WingMaterijal{
			Id:        13,
			Naziv:     "Glet masa",
			Opis:      "Glet masa",
			Obracun:   "Obracun po kilogrammu",
			Jedinica:  "kg",
			Pakovanje: 5 / 1,
			Cena:      18.00,
			Slug:      "glet_masa",
		},
		13: &model.WingMaterijal{
			Id:        14,
			Naziv:     "Građevinski lepak",
			Opis:      "Građevinski lepak",
			Obracun:   "Obracun po kilogrammu",
			Jedinica:  "kg",
			Pakovanje: 5 / 1,
			Cena:      18.00,
			Slug:      "gradjevinski_lepak",
		},
		14: &model.WingMaterijal{
			Id:        15,
			Naziv:     "Spoljni mašinski malter-cementni",
			Opis:      "Spoljni mašinski malter-cementni",
			Obracun:   "Obracun po kilogrammu",
			Jedinica:  "kg",
			Pakovanje: 30,
			Cena:      8.50,
			Slug:      "spoljni_masinski_malter_cementni",
		},
		15: &model.WingMaterijal{
			Id:        16,
			Naziv:     "PK POL",
			Opis:      "PK POL",
			Obracun:   "Obracun po kilogrammu",
			Jedinica:  "kg",
			Pakovanje: 25,
			Cena:      30.00,
			Slug:      "pk_pol",
		},
		16: &model.WingMaterijal{
			Id:        17,
			Naziv:     "PK POL",
			Opis:      "PK POL",
			Obracun:   "Obracun po kilogrammu",
			Jedinica:  "kg",
			Pakovanje: 8,
			Cena:      38.00,
			Slug:      "pk_pol",
		},
		17: &model.WingMaterijal{
			Id:        18,
			Naziv:     "Mašinski malter rinfuz",
			Opis:      "Mašinski malter rinfuz",
			Obracun:   "Obracun po kilogrammu",
			Jedinica:  "kg",
			Pakovanje: 25,
			Cena:      7.00,
			Slug:      "masinski_malter_rinfuz",
		},
		18: &model.WingMaterijal{
			Id:        19,
			Naziv:     "PK-kulir",
			Opis:      "PK-kulir",
			Obracun:   "Obracun po kilogrammu",
			Jedinica:  "kg",
			Pakovanje: 25,
			Cena:      75.00,
			Slug:      "pk_kulir",
		},
		19: &model.WingMaterijal{
			Id:        20,
			Naziv:     "PK AKRIL",
			Opis:      "PK AKRIL",
			Obracun:   "Obracun po kilogrammu",
			Jedinica:  "kg",
			Pakovanje: 25,
			Cena:      70.00,
			Slug:      "pk_akril",
		},
		20: &model.WingMaterijal{
			Id:        21,
			Naziv:     "PK-PLAST",
			Opis:      "PK-PLAST",
			Obracun:   "Obracun po kilogrammu",
			Jedinica:  "kg",
			Pakovanje: 25,
			Cena:      58.00,
			Slug:      "pk_plast",
		},
		21: &model.WingMaterijal{
			Id:        22,
			Naziv:     "Lepak za kamen sivi",
			Opis:      "Lepak za kamen sivi",
			Obracun:   "Obracun po kilogrammu",
			Jedinica:  "kg",
			Pakovanje: 25,
			Cena:      18.00,
			Slug:      "lepak_za_kamen_sivi",
		},
	}

	return
}
